image: debian/stable
packages:
  - rsync
sources:
  - https://git.sr.ht/~bzg/emacs-doctor.com
secrets:
  - 7a38e4c8-2b08-446e-a478-2a114a50db86
tasks:
  - upload: |
      rsync -e "ssh -o StrictHostKeyChecking=no" -av emacs-doctor.com/* bzg.fr:/home/build/emacs-doctor.com/
triggers:
  - action: email
    condition: failure
    to: bzg@gnu.org
