#+title: Ateliers francophones GNU Emacs
#+author: Bastien Guerry
#+options: toc:nil html-preamble:nil html-postamble:nil num:nil html-style:nil
#+html_head: <link rel="stylesheet" type="text/css" href="index.css" />

Nous sommes quelques utilisateurs de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir en visio
ou en présentiel pour apprendre les uns des autres : c'est ouvert aux
non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

* Liste de discussion

Vous pouvez vous inscrire sur [[https://lists.sr.ht/~bzg/emacsfr][la liste de discussion]].

* Forum

Nous avons aussi un [[https://emacs.gnu.re][forum]], n'hésitez pas à échanger.

* Prochaines rencontres

- Paris : jeudi 7 septembre 2023 de 17h30 à 19h (à distance via l'instance BigBlueButton indiquée ci-dessous et en présentiel chez [[https://april.org][l'April]] au 44/46 rue de l'Ouest (cour intérieure) Bâtiment 8, 75014 Paris, [[https://www.openstreetmap.org/export/embed.html?bbox=2.318026721477509%2C48.83606581491022%2C2.320424616336823%2C48.837485234375855&layer=mapnik&marker=48.836775529670504%2C2.3192256689071655][plan]], [[https://www.april.org/reglement-interieur#Code_de_conduite][code de conduite de l'April]])
- Paris : mardi 3 octobre 2023 de 17h30 à 19h
- Paris : jeudi 2 novembre 2023 de 17h30 à 19h
- Paris : mardi 5 décembre 2023 de 17h30 à 19h
- Paris : jeudi 4 janvier 2024 de 17h30 à 19h
- Paris : mardi 6 févier 2024 de 17h30 à 19h
- Paris : jeudi 7 mars 2024 de 17h30 à 19h
- Paris : mardi 2 avril 2024 de 17h30 à 19h

Les rencontres ont lieu sur [[https://bbb.emacsverse.org/b/leo-mqk-ncb-tbr][cette instance de BigBlueButton]].

Vous pouvez télécharger le [[./emacs-paris-meetups.ics][fichier .ics avec les rendez-vous]].

* Comment je m'inscris à un atelier ?

** Pour Paris

Nous faisons des rencontres en ligne.  Il y a parfois des rencontres
physiques chez [[http://inno3.fr][inno3.fr]] au 137 Boulevard de Magenta 75010 Paris ([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]])
de 18h à 22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
sur la liste de discussion =~bzg/emacsfr@lists.sr.ht=.  Pour la visio,
vous pouvez simplement débarquer.

** Pour Montpellier

Envoyez un mot à =emacsem-owner@movoscope.org= et vous serez inscrit.

* Rencontres passées

Nous gardons parfois des notes des soirées passées sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce dépôt]].
