#+title: Ateliers francophones GNU Emacs
#+author: Bastien Guerry
#+options: toc:nil html-preamble:nil html-postamble:nil num:nil html-style:nil
#+html_head: <link rel="stylesheet" type="text/css" href="index.css" />

Nous sommes quelques utilisateurs de [[https://www.gnu.org/software/emacs/][GNU Emacs]] à nous réunir en visio
ou en présentiel pour apprendre les uns des autres : c'est ouvert aux
non-emacsiens, aux débutants, aux utilisateurs avancés et aux
vimistes !

* Liste de discussion

Vous pouvez vous inscrire sur [[https://lists.sr.ht/~bzg/emacsfr][la liste de discussion]].

* Forum

Nous avons aussi un [[https://emacs.gnu.re][forum]], n'hésitez pas à échanger.

* Prochaines rencontres

- Paris : mardi 6 décembre 2022 de 18h à 20h en visio et chez Inno3.

Les rencontres ont lieu sur [[https://bbb.emacsverse.org/b/leo-mqk-ncb-tbr][cette instance de BigBlueButton]], gentiment
fournie par [[https://fosshost.org/][fosshost.org]].

* Comment je m'inscris à un atelier ?

** Pour Paris

Nous faisons des rencontres en ligne.  Il y a parfois des rencontres
physiques chez [[http://inno3.fr][inno3.fr]] au 137 Boulevard de Magenta 75010 Paris ([[http://www.openstreetmap.org/#map=16/48.8818/2.3514][plan]])
de 18h à 22h.

Si vous venez pour la première fois à un atelier IRL, envoyez un mot
sur la liste de discussion =~bzg/emacsfr@lists.sr.ht=.  Pour la visio,
vous pouvez simplement débarquer.

** Pour Montpellier

Envoyez un mot à =emacsem-owner@movoscope.org= et vous serez inscrit.

* Rencontres passées

Nous gardons parfois des notes des soirées passées sur [[https://gitlab.com/bzg2/emacsparis/blob/master/README.org][ce dépôt]].
